<a href="https://colab.research.google.com/github/ramani0527/Pytorch-/blob/main/DL_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

Tensors : A torch.Tesor is  a mulit dimensional matrix containing element of a sigle data type. Work better on GPU and default datatype is float32. Suitable of DeepLeaning than a numpy array.

In [10]:
import numpy as np


**LIST**

In [6]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [7]:
my_list1 =[[1,2,3,4],[6,7,8,9]]
my_list1

[[1, 2, 3, 4], [6, 7, 8, 9]]

Numpy arrays

In [15]:
np1 = np.random.rand(3,4)
np1

array([[0.84213438, 0.54869488, 0.32573707, 0.6360747 ],
       [0.6199114 , 0.85114823, 0.03901014, 0.87725191],
       [0.3189741 , 0.40589486, 0.70318429, 0.75139408]])

In [16]:
np1.dtype

dtype('float64')

**TENSORS**

In [17]:
tensor_2d = torch.rand(3,5)
tensor_2d

tensor([[0.7378, 0.9085, 0.9452, 0.8093, 0.1762],
        [0.5289, 0.3229, 0.7310, 0.9491, 0.8753],
        [0.4399, 0.7926, 0.1252, 0.6484, 0.1990]])

In [19]:
tensor_3d = torch.randn(3,2,3)
tensor_3d

tensor([[[ 0.3659,  0.0524, -0.3531],
         [ 1.1157,  0.2106,  1.1589]],

        [[ 0.0383,  0.1415, -0.2193],
         [-0.3631,  0.6800,  1.8245]],

        [[ 0.4354,  1.7148,  0.1331],
         [-0.7137, -0.2228,  0.8519]]])

In [21]:
tensor_3d.dtype

torch.float32

In [20]:
# Create tensor out of numpy array
my_tens = torch.tensor(np1)
my_tens


tensor([[0.8421, 0.5487, 0.3257, 0.6361],
        [0.6199, 0.8511, 0.0390, 0.8773],
        [0.3190, 0.4059, 0.7032, 0.7514]], dtype=torch.float64)