<a href="https://colab.research.google.com/github/ramani0527/Pytorch-/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np


In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [7]:
# addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [12]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
#exponent   / power of
tensor_a ** 2

tensor([ 1,  4,  9, 16])

In [17]:
#re assignment
tensor_a + tensor_b


tensor([11, 14, 17, 20])

In [18]:
tensor_a

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a.add(tensor_b)

tensor([11, 14, 17, 20])

In [20]:
tensor_a

tensor([ 6,  8, 10, 12])